---
title: "Report with params"
author: "Marina Reixachs Solé"
github: {user: mars13, repo: parameterized-rmarkdown-docker, branch: "main"}
framework: bootstrap
date: "`r format(Sys.time(), '%x')`"
output: 
  html_document:
    includes:
      after_body: footer.html
params:
    input: ''
assets:
  css: 
    - "style.css"
    - "https://fonts.googleapis.com/css2?family=Montserrat"
    - "https://fonts.googleapis.com/css2?family=Inter"
---

```{css, echo = FALSE}
/* Hide author & title*/
.author,.title {
    display: none;
}

/* Position date to the left*/
.date {
  position: right top;
  text-align: right;
}
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(formattable)
```

# Sample report with parameters from command line

The `.Rmd` file is executed as the following:

```{bash, eval = F}
Rscript -e "rmarkdown::render('template_report_cmdline_params.Rmd',params=list('sample_file.tsv'))"
```

If there is any trouble locating pandoc, first identify your pandoc location:

```{r, eval = F}
Sys.getenv("RSTUDIO_PANDOC")
```

Then add the path from that command to your R environment prior to rendering the Rmarkdown:

```{bash, eval = F}
R -e "Sys.setenv(RSTUDIO_PANDOC='path_to_pandoc'); rmarkdown::render('template_report_cmdline_params.Rmd',params=list('sample_file.tsv'))"
```



### Read file 

```{r read_tsv}
df = read.delim(file = params$input)
```

### Report table 

```{r table}
formattable::formattable(df, list(
  Murder =color_tile("white", "firebrick"),
  Rape = color_tile("white", "firebrick"),
  UrbanPop = formatter("span", style = x ~ ifelse(x > 60,
    style(color = "#DE6E4B", font.weight = "bold"), NA)),area(col = c(Assault)) ~ normalize_bar("#7FD1B9", 0.6)
))
```



